### ISSUE TITLE
orangepi3 怎么使用耳机播放声音？

### ISSUE THREAD

**Issue by lingxd** [orangepi-xunlong/linux-orangepi#1]
插入耳机之后  一直是嘟嘟嘟的的声音

**Comment by orangepi-xunlong** [comment]
请尝试轻微的拔插下耳机，具体测试方法请查看对应的用户手册。

用户手册下载地址为：[http://www.orangepi.cn/downloadresourcescn/](http://www.orangepi.cn/downloadresourcescn/)
