### ISSUE TITLE
Connect error: connect error: Transport endpoint is not connected (107)

### ISSUE THREAD

**Issue by w-xiaohei** [orangepi-xunlong/linux-orangepi#10]
i got this error when trying to connect bluetooth on OrangePiZero2. the entire trace is:

root@orangepizero2:/usr/local/lib/python3.8/dist-packages/bluepy# ./bluepy-helper 0
# bluepy-helper.c version 1.3.0 built at 13:48:35 on Jan 13 2022
conn e1:f7:57:48:4a:af random
rsp=$statstate=$tryconndst='e1:f7:57:48:4a:afmtu=h0sec='low
rsp=$statstate=$discmtu=h0sec='low
rsp=$errcode=$connfailemsg='connect error: Transport endpoint is not connected (107)
# Connect error: connect error: Transport endpoint is not connected (107)
conn e1:f7:57:48:4a:af random
rsp=$statstate=$tryconndst='e1:f7:57:48:4a:afmtu=h0sec='low
rsp=$statstate=$discmtu=h0sec='low
rsp=$errcode=$connfailemsg='connect error: Transport endpoint is not connected (107)
# Connect error: connect error: Transport endpoint is not connected (107)

the bluetooth version:

root@orangepizero2:/usr/local/src/bluez# bluetoothctl --version
bluetoothctl: 5.53

**Comment by orangepi-xunlong** [comment]
We can use Blueman to connect bluetooth normally. So bluetooth works fine.
