### ISSUE TITLE
请问如何修改spidev.bufsiz？

### ISSUE THREAD

**Issue by tbfito** [orangepi-xunlong/linux-orangepi#12]
镜像为 Orangepizero_2.0.8_ubuntu_focal_server_linux5.4.65 spi开启 spidev_test无问题 默认bufsiz为4096 如何调节大小？谢谢

**Comment by orangepi-xunlong** [comment]
![图片](https://user-images.githubusercontent.com/10287101/155247448-d7509501-e4d6-402d-aedb-bc301ad4cb6f.png)

你好，试下这个方法。谢谢!

**Comment by tbfito** [comment]
您好 这个方法试过了 buffer size依旧没有更改 请问还有其他的方法吗？

**Comment by tbfito** [comment]
您好 已经解决 可以使用rmmod spidev卸载驱动 再使用modprobe spidev bufsiz=4000000 即可更改bufsiz为4000000
