### ISSUE TITLE
Rebasing onto the mainline linux branches

### ISSUE THREAD

**Issue by katyo** [orangepi-xunlong/linux-orangepi#14]
Rebasing onto the mainline linux branches

Currently the branches at this repository does not based on mainline linux branches, i.e. it has not common history with official linux repository.

It may be quite useful to rebase changes on top of official branches (say from https://github.com/torvalds/linux linux-5.x.y). See raspberry pi linux kernel tree (https://github.com/raspberrypi/linux) and some other.

You may simply fetch needed branches (linux-5.x.y) from mainline linux repo and cherry-pick your commits.

**Comment by orangepi-xunlong** [comment]
Thanks for your advice！
