### ISSUE TITLE
Hdmi orangepi 3 lts - next branch

### ISSUE THREAD

**Issue by afaulkner420** [orangepi-xunlong/linux-orangepi#15]
Is hdmi screen working for orangepi 3 lts under the new 5.16 kernel? 
Im able to build, but when i boot it, the leds do the right thing, but i get a totally black screen. nothing happens.
It seems to work perfectly for Armbian. Which i have now been able to successfully bring up properly. eveything works except bluetooth, crashes when i try to turn it on. Any ideas on that also?

**Comment by orangepi-xunlong** [comment]
Hi, Orange Pi 3 LTS Linux5.16 HDMI is fine.

![图片](https://user-images.githubusercontent.com/10287101/162712568-aed5d790-6587-4f71-a596-7e43dfd95b4a.png)

Can you switch HDMI resolution here？

![图片](https://user-images.githubusercontent.com/10287101/162712721-c2f7e932-1efb-48a7-8f37-c555690e86ff.png)

**Comment by afaulkner420** [comment]
It's totally black/blank from boot. Nothing shows up. I don't get a desktop environment or anything?

**Comment by orangepi-xunlong** [comment]
Can you switch HDMI resolution on linux5.15？

**Comment by afaulkner420** [comment]
Not too sure on that. Haven't tried. Last time I built your current brach it was at 5.10.
I'm now running 5.15 and 5.16 through armbian. 
My repositories are up on my github.
https://github.com/afaulkner420
I'm able to build and run ambian perfectly as far as I'm aware.

**Comment by afaulkner420** [comment]
I'm unable to test anything until later today. One issue I have noticed though, is with panfrost. 
121.584328] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x715ec00, tail=0x715ec00
[  121.635491] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x715de00, tail=0x715de00
[  121.637797] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x71724c0, tail=0x71724c0
[  181.666563] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x7171280, tail=0x7171280
[  181.687731] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x7173bc0, tail=0x7173bc0
[  241.728792] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x7172900, tail=0x7172900
[  241.744175] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x711f8c0, tail=0x711f8c0
[  241.750813] panfrost 1800000.gpu: js fault, js=0, status=INSTR_INVALID_PC, head=0x7172f00, tail=0x7172f00

**Comment by afaulkner420** [comment]
Not to sure if this is linked at all?

**Comment by orangepi-xunlong** [comment]
Sorry, I can't solve GPU-related problems.
