### ISSUE TITLE
no hdmi audio on orange-pi-5.16-sunxi64 on h616 orange-pi-zero2

### ISSUE THREAD

**Issue by warpme** [orangepi-xunlong/linux-orangepi#16]
Hi,

I trying to get hdmi audio using orange-pi-5.16-sunxi64 branch on orange-pi-zero2 (h616).
It not works unfortunatelly.
Looking on dmesg I see:
`sunxi-hdmi soc:hdmi-audio@1: snd_soc_register_card failed `
On orange-pi-5.13-sunxi64 i have working hdmi audio (and no any sunxi-hdmi errors in dmesg)
It looks - to me - like orange-pi-5.16-sunxi64 has regression ?

**Comment by orangepi-xunlong** [comment]
Hi, Please first compile the test image with orangepi-build, thanks!

![图片](https://user-images.githubusercontent.com/10287101/163739552-5fa43258-6913-49d4-8c05-c73dd1f2f4be.png)
