### ISSUE TITLE
Compilation error in xradio wireless driver

### ISSUE THREAD

**Issue by hartogjr** [orangepi-xunlong/linux-orangepi#2]
Hi,
When cross compiling the 5.4 branch with the default `orangepi_defconfig`, I encounter the following error when the xradio wireless driver is being built:
```
In file included from drivers/net/wireless/xradio/fwio.c:17:
drivers/net/wireless/xradio/xradio.h:206:26: error: field ‘pm_state’ has incomplete type
  206 |  struct xradio_pm_state  pm_state;
      |                          ^~~~~~~~
drivers/net/wireless/xradio/xradio.h:364:29: error: field ‘pm_state_vif’ has incomplete type
  364 |  struct xradio_pm_state_vif pm_state_vif;
      |                             ^~~~~~~~~~~~
```
Please find the generated config here:
[orangepi_defconfig_5.4.txt](https://github.com/orangepi-xunlong/linux-orangepi/files/6017402/orangepi_defconfig_5.4.txt)

I am using a Gentoo cross-compilation toolchain:
* cross-aarch64-unknown-linux-gnu/binutils-2.34-r2
* cross-aarch64-unknown-linux-gnu/gcc-9.3.0-r2
* cross-aarch64-unknown-linux-gnu/glibc-2.32-r5
* cross-aarch64-unknown-linux-gnu/linux-headers-5.4-r1

Please let me know if you need more info. I am building the kernel to run on an Orange Pi PC2. Disabling all the drivers that cause compilation errors gives me a runnable kernel, but the Orange Pi PC2 locks up when I put load on the CPU, probably because I had to disable the CPU thermal throttling driver as well. But let's stick to this issue for now ;-)
Kind regards,
Simon de Hartog

**Comment by orangepi-xunlong** [comment]
Please use [orangepi-build](https://github.com/orangepi-xunlong/orangepi-build) to compile the kernel or image, thanks!
