### ISSUE TITLE
Orange pi zero 2 can not reboot or shutdown

### ISSUE THREAD

**Issue by tarekmuallim** [orangepi-xunlong/linux-orangepi#26]
Hello,

When I am trying to shutdown or reboot, it stuck at shutdown after giving message:
`systemd-shutdown[1]: Waiting for process: grep, lscpu`

Any idea why this is happening?

The OS image:
Orangepizero2_3.0.6_ubuntu_jammy_desktop_xfce_linux5.16.17

**Comment by orangepi-xunlong** [comment]
[sun50i-h616-orangepi-zero2.zip](https://github.com/orangepi-xunlong/linux-orangepi/files/10244794/sun50i-h616-orangepi-zero2.zip)

Please update this dtb.
