### ISSUE TITLE
Where is 3.10 kernel for Orange PI 3 with an actual config for PCIe?

### ISSUE THREAD

**Issue by SergeyStaroletov** [orangepi-xunlong/linux-orangepi#31]
It seems that Orange PI 3 has a workable PCIe, I checked the voltages and they are correct, but there are no devices with the fresh kernel, so I concluded that it is a software problem to get it work with the fresh kernels. 
Then I loaded an .img with 3.10 from old setups and it was able to run 'lspci' and it showed me some my devices. 
But there is no branch here for 3.10 sources. Then I found it in the Android sources and it is compilable. I need at least a working config. It does not exist anywhere, nor in /boot nor in /proc. Do you have one?
Also it is interesting, if there any diif of changes for the only one working driver rtl 8822 against its original sources?

**Comment by orangepi-xunlong** [comment]
https://github.com/orangepi-xunlong/OrangePiH6_kernel
