### ISSUE TITLE
Zero2 拷贝大文件时死机

### ISSUE THREAD

**Issue by garlicsoft** [orangepi-xunlong/linux-orangepi#7]
我有一个硬盘座插两了两块硬盘(exfat)，另外一个移动硬盘(ntfs)插在Zero2上，用的是官方镜像。
在拷贝大文件时出现如下情况
![IMG_2102](https://user-images.githubusercontent.com/4339630/126862172-a661fb48-c668-42b9-af70-74e74531fa6b.jpg)
直接死机（我接了hdmi，键盘没反应了）

再次测试了一下，scp拷贝硬盘座上的文件(exfat)到本地电脑成功，删除文件后scp把本地文件再拷回Zero2里原位置时失败。直接死机。
![IMG_8504](https://user-images.githubusercontent.com/4339630/126862618-d94104b0-74c5-439d-988a-9c5fefc03044.JPG)

**Comment by orangepi-xunlong** [comment]
供电充足吗？

**Comment by garlicsoft** [comment]
> 

供电应该是充足的（因为反复测试过多次），不知道是不是我的板子有问题
后来放弃了，换回zero。
